### ISSUE TITLE
CSS-modules: composes

### ISSUE THREAD

**Issue by kenOfYugen** [KidkArolis/jetpack#50]
Jetpack is awesome @KidkArolis !
I have created a test case for CSS-modules [here](https://github.com/kenOfYugen/jetpack), `npm t` should point it out.
CSS-modules seem to work, but I can't get `composes` to inherit properties.
No matter what I tried, I couldn't fix it, hence the issue report.
```css
.parent {
  background-color: black;
  color: green;
}

.child {
  composes: parent;
  color: red;
}
```

Expected:
```css
.child {
  background-color: black;
  color: red;
}
```

Actual:
```css
.child {
  color: red;
}
```
